version: 0.0
os: windows
files:
  - source: /
    destination: C:\inetpub\wwwroot\MVC_00013940

hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.ps1
      timeout: 300
      runas: Administrator
  ApplicationStop:
    - location: scripts/ApplicationStop.ps1
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: scripts/AfterInstall.ps1
      timeout: 300
      runas: Administrator
  ApplicationStart:
    - location: scripts/ApplicationStart.ps1
      timeout: 300
      runas: Administrator
